Source-Machine-Ent/after-school-algorithm-gajyeowa

.gitignore
ningpop/level2/문자열_압축.py

closed #9 
- 풀이 일자: 2022.07.28
- 풀이 시간: 35분 15초
- 채점 결과: 정답
- 시간복잡도: O(NlogN)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/60057
토큰 길이를 글자수 1부터 문자열 길이의 반만큼의 범위를 돌면서 겹치는지 확인하는 방식을 사용하였고, 정답 처리 되었습니다.

[#9] 문자열 압축

---

Orlando/level2/Solution_문자열압축.java

문자열 압축
- 풀이 일자: 2022.07.28
- 풀이 시간: 79분 
- 채점 결과: 런타임 에러 -> 저답
- 시간복잡도: 
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/60057
문제의 조건을 이해하는데 시간을 많이 뺐겼습니다

프로그래머스 문자열 압축

---

Hprogram/level2/문자열압축.js

문자열 압축
- 풀이 일자: 2022.07.29
- 풀이 시간: 약 20분 00초
- 채점 결과: 오답->정답
- 시간복잡도:  O(nlogn)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/60057
오답 사유 : 처음에 그 시작 문자열 크기를 절반을 나누는게 아니라 해당 i 증가값으로 나눠서 동작 횟수의 부족으로 인해 오답처리.
개선 : 제공되는 s의 크기의 절반 이후부터는 계산 할 필요가 없기 때문에 해당 길이의 절반 만큼만 반복문이 동작하도록 수정 후 정답.

문자열 압축 문제풀이

---

210/level3/추석트래픽.java

programmers 추석트래픽

---

Orlando/level3/Solution_추석트래픽.java

17676 추석 트래픽
- 풀이 일자: 2022.07.30
- 풀이 시간: 142분
- 채점 결과: 오답
- 시간복잡도: $O(n^2)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/17676
파싱 방식과 접근 방식을 고민하느라 시간이 많이 들어간 것 같습니다.

[2022-07-30] 추석 트래픽

---

210/level1/로또의최고순위와최저순위.java

programmers 로또의최고순위와최저순위

---

ningpop/level1/로또의_최고_순위와_최저_순위.py

closed #18 
- 풀이 일자: 2022.08.01
- 풀이 시간: 8분 58초
- 채점 결과: 정답
- 시간복잡도: O(N)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/77484
로또번호를 차례로 탐색하며 0인지 아닌지 우선 판단한 후, 0이 아니라면 1등 로또 번호에 있는지 확인하는 과정으로 풀이하였고, 정답 처리 되었습니다.

[#18] 로또의 최고 순위와 최저 순위 - 정답

---

Orlando/level2/Solution_오픈채팅방.java

42888 오픈 채팅방
- 풀이 일자: 2022.08.02
- 풀이 시간: 43분
- 채점 결과: 정답
- 시간복잡도: $O(N)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888
자바로 문자열 다루는게 생각보다 까다롭습니다.

[2022-08-02] 오픈 채팅방

---

ningpop/level2/오픈채팅방.py

closed #29 
- 풀이 일자: 2022.08.04
- 풀이 시간: 21분 42초
- 채점 결과: 정답
- 시간복잡도: O(N)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42888
입력으로 들어온 리스트를 순회하면서 user table을 만들고 최신화한 뒤, enter, leave에 따라서 기록을 표현하는 방식으로 풀이하였습니다.

[#29] 오픈채팅방 - 정답

---

210/level3/N으로표현.java

programmers N으로표현

---

210/level1/신규아이디추천.java

programmers  신규아이디추천

---

Orlando/level1/Solution_새로운아이디.java

72410 신규 아이디 추천
- 풀이 일자: 2022.08.08
- 풀이 시간: 49분
- 채점 결과: 정답
- 시간복잡도: $O(N^2)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/72410
step4와 step6에서 조건을 빠뜨린게 있어서 조금 더 시간이걸렸습니다.

[2022-08-08]programmers 새로운 아이디

---

210/extra/level2/양궁대회.java

programmers 양궁대회

---

jiho/level2/카카오프렌즈컬러링북.java

카카오프렌즈 컬러링북
- 풀이 일자: 2022.08.10
- 풀이 시간: 120분 00초
- 채점 결과: 정답
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/1829
dfs라는 개념 자체를 처음 봐서 인터넷에 정보를 찾아보고, 이해하고, 푸는 데까지 시간이 많이 들어갔던 것 같습니다.

카카오프렌즈컬러링북

---

210/level2/카카오프렌즈컬러링북.java

programmers 카카오프렌즈컬러링북

---

ningpop/level1/신규_아이디_추천.py

closed #34 
- 풀이 일자: 2022.08.10
- 풀이 시간: 29분 36초
- 채점 결과: 정답
- 시간복잡도: O(N)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/72410
정규식에 익숙하지 않아 풀이시간이 30분 가까이 소요되었습니다.

[#34] 신규 아이디 추천 - 정답

---

210/level1/test.txt
Orlando/level2/Solution_카카오프렌즈컬러링북.java

카카오프렌즈 컬러링 북
- 풀이 일자: 2022.08.12
- 풀이 시간: 45분 
- 시간복잡도: $O(N^2)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/1829
프로그래머스에서 static 변수를 초기화 할때는 무조건 메서드 내에서 해야합니다.
이떄문에 시간이 다소 소요되었습니다

[2022-08-12] 카카오프렌즈 컬러링북

---

ningpop/level3/입국심사.py

closed #45 
- 풀이 일자: 2022.08.13
- 풀이 시간: 37분 45초
- 채점 결과: 정답
- 시간복잡도: O(NlogN)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/43238
이분탐색을 활용하였습니다. `start = 0`, `end = 예상되는 최대 걸리는 시간`으로 지정하고, `mid`값을 움직여가며 `mid`값에 대한 모두 입국심사가 끝났는지를 판단하였고, 정답 처리 되었습니다.

[#45] 입국심사 - 정답

---

210/level1/숫자문자열과영단어.java

programmers 숫자문자열과영단어

---

Orlando/level1/Solution_숫자문자열과단어.java

81301:  숫자 문자열과 영단어
- 풀이 일자: 2022.08.16
- 풀이 시간: 12분
- 채점 결과: 정답
- 시간복잡도: $O(N^2)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/81301
자바로 isDigit을 처음 써봤네요

[2022-08-16] programmers : 81301

---

210/level3/가장먼노드.java

programmers 가장먼노드

---

JunJangE/level3/가장 먼 노드.kt

가장 먼 노드.kt

---

ningpop/level1/숫자_문자열과_영단어.py

closed #56 
- 풀이 일자: 2022.08.20
- 풀이 시간: 9분 30초
- 채점 결과: 정답
- 시간복잡도: O(N)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/81301
딕셔너리로 영단어를 숫자로 바꿀 테이블을 미리 만들어두고 한글자씩 검사하면서 단어를 만든 뒤, 테이블에 있다면 대체하는 방식으로 풀이하였습니다. 정답 처리 되었습니다.

[#56] 숫자 문자열과 영단어 - 정답

---

210/level1/키패드누르기.java

programmers 키패드누르기

---

210/extra/level1/완주하지못한선수.java

programmers 완주하지못한선수

---

Orlando/level1/Solution_키패드누르기.java

LV1.키패드 누르기
- 풀이 일자: 2022.08.24
- 풀이 시간: 72분
- 시간복잡도: $O(N)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/67256
처음에 왼손과 오른손만 신경쓰다가 가운데를 처리하는 부분을  다시 구현하는 과정에서 어려움이 있었습니다.
잠들기전, 내일은 꼭 나름 식을 세워서 배열없이 풀자라는 생각을 하며 생각해서 풀어보았습니다.

[2022-08-24] programmers : lv1 키패드 누르기

---

210/level2/멀쩡한사각형.java

programmers 멀쩡한사각형

---

ningpop/level1/키패드_누르기.py

closed #66 
- 풀이 일자: 2022.08.24
- 풀이 시간: 19분 39초
- 채점 결과: 정답
- 시간복잡도: O(N)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/67256
키패드의 좌표 위치를 딕셔너리로 만들어 둔 후, 입력 배열을 순회하면서 현재 왼손/오른손의 위치를 저장하며 요구사항대로 풀이하였습니다. 정답 처리 되었습니다.

[#66] 키패드 누르기 - 정답

---

210/extra/level2/스킬트리.java

programmers 스킬트리

---

210/level3/브라이언의고민.java

programmers 브라리언의고민

---

ningpop/level2/멀쩡한_사각형.py

closed #70 
- 풀이 일자: 2022.08.26
- 풀이 시간: 48분 26초
- 시간복잡도: O(1)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/62048
1. gcd의 배수로 반복됨을 이해하였습니다. 뒤이어 기울기 값이 width가 1일때 닿게되는 height인 것을 알아내고 기울기에 width 만큼 곱하는 방법을 사용하였으나 width나 height가 홀수일 경우 반례로 작용하여 오답 처리 되었습니다.
2. 고민하다 결국 풀이를 참고하였고, width와 height를 gcd로 나누고 1을 뺀 값이 gcd로 나눈 작은 사각형에서 잘려지는 사각형의 갯수임을 이해하였습니다. 이후 정답처리 되었습니다.

[#70] 멀쩡한 사각형 - (오답 -> 정답)

---

210/extra/level1/크레인인형뽑기게임.java

programmers 크레인인형뽑기게임

---

JunJangE/level1/크레인 인형뽑기 게임.kt

크레인 인형뽑기 게임

---

ningpop/level1/크레인_인형뽑기_게임.py

closed #76 
- 풀이 일자: 2022.08.30
- 풀이 시간: 27분 12초
- 채점 결과: 정답
- 시간복잡도: O(N^2)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/64061
2차원 배열을 다루는 간단한 문제였으나, indexing을 하는데에 헛짓거리를 하는 바람에 너무 긴 풀이 시간이 소요되었습니다. 정답 처리 되었습니다.

[#76] 크레인 인형뽑기 게임 - 정답

---

Orlando/level1/.idea/.gitignore
Orlando/level1/.idea/dbnavigator.xml
Orlando/level1/.idea/misc.xml
Orlando/level1/.idea/modules.xml
Orlando/level1/.idea/vcs.xml
Orlando/level1/Solution_크레인인형뽑기기계.java
Orlando/level1/level1.iml

크레인 인형 뽑기
- 풀이 일자: 2022.08.30
- 풀이 시간: 16분
- 채점 결과: 정답
- 시간복잡도: $O(N^2)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/64061
없었습니다!

[2022-08-30] programmers level1 크레인인형뽑기

---

JunJangE/level2/가장 큰 수.kt

Create 가장 큰 수.kt

---

210/level2/124나라의숫자.java

programmers 124나라의숫자

---

JunJangE/level1/성격 유형 검사하기.kt

Create 성격 유형 검사하기.kt

---

210/level1/없는숫자더하기.java

programmers 없는숫자더하기

---

JunJangE/level1/없는 숫자 더하기.kt

없는 숫자 더하기.kt

---

210/level2/기능개발.java

programmers 기능개발

---

210/extra/level2/두큐합같게만들기.java

programmers 두큐합같게만들기

---

JunJangE/level2/기능 개발.kt

Create 기능 개발.kt

---

JunJangE/level3/디스크 컨트롤러.kt

Create 디스크 컨트롤러.kt

---

ningpop/level2/124_나라의_숫자.py

closed #81 
- 풀이 일자: 2022.09.11
- 풀이 시간: 63분 32초
- 시간복잡도: O(logN)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/12899
1. 3진법과 비슷한 구조임을 이해하고 3으로 나누어 떨어질 경우, 4로 치환 후 앞자리를 줄이는 방식을 사용하였으나 오답 처리 되었습니다.
2. 풀이를 확인 후, 3으로 나누어 떨어질 경우 4로 치환 후 나눌 대상을 1 감소시켜 계산을 이어나가는 방식을 사용하여 정답 처리 되었습니다.

[#81] 124 나라의 숫자 - (오답 -> 정답)

---

ningpop/level1/없는_숫자_더하기.py

closed #91 
- 풀이 일자: 2022.09.11
- 풀이 시간: 4분 39초
- 채점 결과: 정답
- 시간복잡도: O(N)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/86051
0부터 9까지의 index값으로 숫자가 등장했는지를 확인 후, 등장하지 않은 숫자를 더하여 풀이하였고 정답 처리 되었습니다.

[#91] 없는 숫자 더하기 - 정답

---

210/level3/디스크컨트롤러.java

programmers 디스크컨트롤러

---

210/level1/음양더하기.java

programmers 음양더하기

---

210/extra/level2/주차요금계산.java

programmers 주차 요금 계산

---

210/level2/더맵게.java

programmers

---

210/level3/정수삼각형.java

programmers 정수삼각형

---

ningpop/level2/기능개발.py

closed #92 
- 풀이 일자: 2022.09.17
- 풀이 시간: 55분 03초
- 시간복잡도: O(N)
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/42586
1. 각 작업의 소요 시간 배열을 계산해 한번에 완료 처리 될 수 있는 개수를 count 하는 방법을 사용하였으나, 오답 처리 되었습니다. 또한, 정리되지 않은 로직으로 인해 개선이 불가능했습니다.
2. 다시 개선 가능한 정리된 로직으로 구현하였고, 히든 테스트 케이스에 막혀 여러번 오답 처리 되었습니다.
3. 테스트 케이스를 추가하여 확인 결과, 증가하는 날짜수를 계산하는 방법에 오류가 있어 수정하였고, 정답 처리 되었습니다.

[#92] 기능개발 - (오답 -> 정답)

---

JunJangE/level3/정수 삼각형.py

Create 정수 삼각형.py

---

210/level1/내적.java

programmers 내적

---

210/extra/level2/피로도.java

programmers 피로도

---

210/level2/타겟넘버.java

programmers 타겟넘버

---

210/extra/level2/n^2배열자르기.java

programmers n^2배열자르기

---

210/level1/소수만들기.java

programmers 소수만들기

---

Orlando/level1/Solution_소수만들기.java

12977 소수 만들기
- 풀이 일자: 2022.09.26
- 풀이 시간: 17분
- 채점 결과: 정답
- 시간복잡도: $O(N)$
- 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/12977
킹 이즈 백

[2022-09-26] Programmers lv1 : 소수 만들기

---

210/level2/짝지어제거하기.java

programmers 짝지어제거하기

---

210/level3/네트워크.java

programmers 네트워크

---

210/level1/폰켓몬.java

programmers 폰켓몬

---

210/level1/모의고사.java

programmers 모의고사

---

210/level2/거리두기확인하기.java

programmers 거리두기 확인하기

---

210/level2/수식최대화.java

programmers 수식최대황

---

210/level3/불량사용자.java

proogrammers

---

210/level2/튜플.java

programmers 튜플

---

210/extra/softeer/2023-pre.java

softeer 1차 기출(영역 구분)

---

210/level2/순위검색.java
210/level2/후보키.java

programmers 후보키

---

210/level1/성격유형검사하기.java

programmers 성격 유형 검사하기

---

210/level2/줄서는법.java

programmers 줄서는법

---

210/level2/롤케이크자르기.java

programmers 롤케이크자르기

---

210/level2/2xn타일링.java

programmers 2xn 타일링

---

210/level2/할인행사.java

programmers 할인행사

---

210/level2/혼자놀기의달인.java

programmers 혼자놀기의달인
